[pytest]
testpaths = tests
filterwarnings =
    ignore::DeprecationWarning:matplotlib.*
    ignore::DeprecationWarning:plotly.*
    ignore::DeprecationWarning:sklearn.*
    ignore::FutureWarning:pandas.*
    ignore::DeprecationWarning:faiss.*
    ignore::RuntimeWarning:numpy.*
    ignore:.*SwigPy.*:DeprecationWarning
    ignore:.*parseString.*:DeprecationWarning
    ignore:.*resetCache.*:DeprecationWarning
    ignore:.*enablePackrat.*:DeprecationWarning
    ignore:.*engine.*deprecated.*:DeprecationWarning
