# Configuration file for the Sphinx documentation builder.
#
# PAMOLA.CORE — Privacy-Preserving AI Data Processors
# (C) 2024 Realm Inveo Inc. and DGT Network Inc.
# License: BSD 3-Clause
#
# Full documentation: https://www.sphinx-doc.org/en/master/usage/configuration.html

import ast
import logging
import os
import sys
from pathlib import Path

# ---------------------------------------------------------------------------
# Path setup
# ---------------------------------------------------------------------------
# Insert the repository root *before* sys.path so that Sphinx autodoc can
# import pamola_core without requiring the package to be installed.
sys.path.insert(0, os.path.abspath(".."))

# ---------------------------------------------------------------------------
# Logging filter — suppress duplicate-object description warnings
# ---------------------------------------------------------------------------
# "duplicate object description" is emitted when re-exported symbols in
# __init__.py are documented twice.  Sphinx 8.2 emits this without a type tag
# so suppress_warnings cannot catch it; a logging filter is required.
# ---------------------------------------------------------------------------
class _SuppressDuplicateObject(logging.Filter):
    def filter(self, record: logging.LogRecord) -> bool:
        return "duplicate object description" not in record.getMessage()


logging.getLogger("sphinx").addFilter(_SuppressDuplicateObject())

# ---------------------------------------------------------------------------
# Project information
# ---------------------------------------------------------------------------
project = "PAMOLA.CORE"
copyright = "2024, Realm Inveo Inc. and DGT Network Inc."
author = "Realm Inveo Inc. and DGT Network Inc."

# Read version from pamola_core._version so the docs always match the package.
try:
    from pamola_core._version import __version__ as _version
    version = ".".join(_version.split(".")[:2])   # e.g. "0.1"
    release = _version                             # e.g. "0.1.0"
except Exception:
    version = "0.0"
    release = "0.0.1"

# ---------------------------------------------------------------------------
# General configuration
# ---------------------------------------------------------------------------
extensions = [
    "sphinx.ext.autodoc",       # Core: generate API docs from docstrings
    "sphinx.ext.napoleon",      # Google- and NumPy-style docstring support
    "sphinx.ext.viewcode",      # Add [source] links to every documented item
    "sphinx.ext.autosummary",   # Auto-generate summary tables + stub pages
    "sphinx_autodoc_typehints", # Generate param/return docs from type hints
]

templates_path = ["_templates"]

# Glob patterns of files/directories that Sphinx should NOT process.
# We explicitly list the existing Obsidian / markdown documentation
# directories so they coexist with Sphinx without conflicts.
exclude_patterns = [
    "_build",
    "_autosummary",
    "Thumbs.db",
    ".DS_Store",
    # Existing non-Sphinx documentation (Obsidian vault, markdown specs)
    ".obsidian",
    "en",
    "ru",
    "specs",
    "mocks",
    "manifest",
    "common",
    # Private module stubs generated by autosummary (e.g. _version)
    "generated/pamola_core._*",
]

# ---------------------------------------------------------------------------
# Autodoc configuration
# ---------------------------------------------------------------------------
autodoc_default_options = {
    "members": True,
    "undoc-members": False,      # Only show members that have docstrings
    "show-inheritance": True,
    "member-order": "bysource",
}

# Display type hints in the description body, not crammed into the signature.
autodoc_typehints = "description"
autodoc_typehints_description_target = "documented"

# sphinx-autodoc-typehints: generate param/return docs from type hints
# even when a function has no docstring or an incomplete one.
always_document_param_types = True
typehints_document_rtype = True
typehints_use_rtype = False         # keep return type in description, not :rtype:
simplify_optional_unions = True     # render Optional[X] as X, optional

# Include the __init__ docstring as part of the class docstring.
autoclass_content = "both"

# Prevent class methods and attributes from creating sidebar TOC entries.
# Methods remain visible on the class page but do not clutter the navigation.
# Introduced in Sphinx 5.2 — safe with Sphinx 9.x.
toc_object_entries = False

# Show bare class/function names instead of fully-qualified module.Class names
# in the sidebar and page headings.
add_module_names = False

# ---------------------------------------------------------------------------
# Autosummary configuration
# ---------------------------------------------------------------------------
# Sphinx will automatically create stub .rst files for every entry listed in
# an ``.. autosummary::`` directive that has a ``:toctree:`` option.
autosummary_generate = True
autosummary_generate_overwrite = True    # Regenerate stubs on every build
autosummary_imported_members = True      # Include re-exported symbols in summary tables

# ---------------------------------------------------------------------------
# Mock imports for all heavy / optional dependencies
# ---------------------------------------------------------------------------
# Prevents sphinx-build from failing in environments where the full
# production dependency stack is not installed (e.g. CI documentation jobs).
autodoc_mock_imports = [
    # ── Data processing ────────────────────────────────────────────────────
    "pandas",
    "dask",
    "numpy",
    "pyarrow",
    "scipy",
    # ── Machine learning ───────────────────────────────────────────────────
    "torch",
    "sklearn",
    # ── NLP ────────────────────────────────────────────────────────────────
    "spacy",
    "nltk",
    "langdetect",
    "fasttext",
    # ── Visualisation ──────────────────────────────────────────────────────
    "matplotlib",
    "seaborn",
    "plotly",
    "kaleido",
    "wordcloud",
    # ── Record linkage / similarity ────────────────────────────────────────
    "recordlinkage",
    "rapidfuzz",
    "faiss",
    "datasketch",
    # ── Synthetic data ─────────────────────────────────────────────────────
    "faker",
    "sdv",
    # ── Cryptography / security ─────────────────────────────────────────────
    "cryptography",
    "bcrypt",
    "base58",
    # ── Validation / serialisation ─────────────────────────────────────────
    "pydantic",
    "yaml",
    "deepdiff",
    "diff_match_patch",
    # ── Image / file formats ───────────────────────────────────────────────
    "PIL",
    "openpyxl",
    "xlrd",
    "ijson",
    # ── Telephony / locale ─────────────────────────────────────────────────
    "phonenumbers",
    # ── Utilities ──────────────────────────────────────────────────────────
    "psutil",
    "chardet",
    "cachetools",
    "rstr",
    "multidict",
    "decouple",
    "uvicorn",
    "requests",
]

# ---------------------------------------------------------------------------
# Napoleon (Google / NumPy docstring) configuration
# ---------------------------------------------------------------------------
napoleon_google_docstring = True
napoleon_numpy_docstring = True           # Source uses NumPy-style throughout
napoleon_include_init_with_doc = True
napoleon_include_private_with_doc = False
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = False
napoleon_use_admonition_for_notes = False
napoleon_use_rtype = False      # sphinx_autodoc_typehints handles :rtype: via typehints_document_rtype
napoleon_preprocess_types = True

# ---------------------------------------------------------------------------
# Warning suppression
# ---------------------------------------------------------------------------
# Suppress the duplicate cross-reference warning caused by BaseOperation being
# exported at three levels (pamola_core, pamola_core.utils, pamola_core.utils.ops.op_base).
# This is a known library design issue and does not affect generated HTML.
suppress_warnings = [
    "ref.python",           # duplicate Python cross-references (BaseOperation)
    "autosummary",          # autosummary stub-generation noise
    "app.add_directive",    # directive re-registration
    "ref.doc",              # orphaned document references
    "py.duplicate_object",  # duplicate object descriptions from re-exported symbols
]

# ---------------------------------------------------------------------------
# HTML output
# ---------------------------------------------------------------------------
# alabaster is bundled with every Sphinx installation; no extra package needed.
html_theme = "alabaster"

html_theme_options = {
    "description": "Privacy-preserving data operations for AI pipelines",
    "github_user": "DGT-Network",
    "github_repo": "PAMOLA",
    "github_banner": True,
    "fixed_sidebar": True,
    "sidebar_width": "280px",
    "page_width": "1100px",
}

html_title = f"PAMOLA.CORE {release}"
html_short_title = "PAMOLA.CORE"
html_static_path = ["_static"]

# ---------------------------------------------------------------------------
# intersphinx (cross-references to external projects)
# ---------------------------------------------------------------------------
# Uncomment to enable cross-references to pandas, Python stdlib, etc.
# extensions += ["sphinx.ext.intersphinx"]
# intersphinx_mapping = {
#     "python": ("https://docs.python.org/3", None),
#     "pandas": ("https://pandas.pydata.org/docs/", None),
#     "numpy":  ("https://numpy.org/doc/stable/", None),
# }

# ---------------------------------------------------------------------------
# Auto-discovery: public submodules → docs/index.rst
# ---------------------------------------------------------------------------
# Parses pamola_core/__init__.py with ast to find every top-level
# ``from pamola_core.X import ...`` statement, then writes docs/index.rst
# with a complete autosummary directive listing all public modules.
#
# Writing to index.rst directly (rather than a separate include fragment)
# is required because Sphinx's autosummary pre-scan only processes files
# it discovers as source documents.  A ``.. include::`` fragment is
# expanded by docutils at parse time — after the pre-scan — so stubs
# would never be generated from an included file.
#
# Developers never need to touch index.rst when new public submodules
# are added to pamola_core/__init__.py: the next sphinx-build picks
# them up automatically.
# ---------------------------------------------------------------------------

_INDEX_RST_TEMPLATE = """\
PAMOLA Core API Reference
=========================

**PAMOLA Core** is an open-source Python library for privacy-preserving data
operations developed by `Realm Inveo Inc. <https://realminveo.com>`_ and
`DGT Network Inc. <https://dgt.world>`_.

Complete reference for every public symbol exported by ``pamola_core``.
All public APIs are importable directly from the top-level package.

Quick Example
-------------

.. code-block:: python

   import pamola_core as pc

   df = pc.read_csv("data.csv")
   op = pc.FullMaskingOperation(...)
   result = op.execute(df)


API Reference
-------------

.. autosummary::
   :toctree: generated

{entries}

----

Indices and Tables
------------------

* :ref:`genindex`
* :ref:`modindex`
* :ref:`search`
"""


def _discover_public_submodules() -> list:
    """Return ordered list of top-level public submodule dotted names.

    Reads pamola_core/__init__.py via ast and collects every unique
    ``pamola_core.X`` name found in ImportFrom nodes, preserving the
    order in which they first appear.
    """
    init_path = Path(__file__).parent.parent / "pamola_core" / "__init__.py"
    source = init_path.read_text(encoding="utf-8")
    tree = ast.parse(source)

    seen: set = set()
    modules: list = []
    for node in ast.walk(tree):
        if isinstance(node, ast.ImportFrom):
            if node.module and node.module.startswith("pamola_core."):
                # Keep only the first two parts: pamola_core.X
                top_sub = ".".join(node.module.split(".")[:2])
                # Skip private submodules (e.g. pamola_core._version)
                if top_sub.split(".")[-1].startswith("_"):
                    continue
                if top_sub not in seen:
                    seen.add(top_sub)
                    modules.append(top_sub)
    return modules


def _write_index_rst() -> None:
    """Write docs/index.rst from the discovered public submodules.

    The file contains a complete ``.. autosummary::`` directive that lists
    ``pamola_core`` followed by every public submodule.  No ``:recursive:``
    flag is used: deep sub-packages are documented within each module's own
    stub page (via the autosummary template), not promoted into the
    top-level sidebar.
    """
    modules = _discover_public_submodules()
    entry_lines = ["   pamola_core"] + [f"   {m}" for m in modules]
    content = _INDEX_RST_TEMPLATE.format(entries="\n".join(entry_lines))

    index_path = Path(__file__).parent / "index.rst"
    index_path.write_text(content, encoding="utf-8")


_write_index_rst()


